/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import login.frmDashboard;
import steamatic.dao.AlmacenDAO;
import steamatic.dao.CompraDAO;
import steamatic.interfaces.IAlmacen;
import steamatic.interfaces.ICompra;
import steamatic.interfaces.IMetodosFormulario;
import steamatic.model.dto.AlmacenDTO;
import steamatic.model.dto.CompraDTO;
import steamatic.utils.Alerts;
import steamatic.utils.StematicConstants;

/**
 *
 * @author RojeruSan
 */
public class pnlCompras extends javax.swing.JPanel implements IMetodosFormulario {

    private Alerts alerts = new Alerts();
    private CompraDTO compraDTO;
    private ICompra icompra = new CompraDAO();
    private Vector encabezado = new Vector();
    private DefaultTableModel model = null;
    public static String id;

    /**
     * Creates new form pnlHome
     */
    public pnlCompras() {
        initComponents();
        this.limpiar();
        this.obtener_compras();
        this.ocultar_boton(true);
        this.lbl_id.setVisible(false);
        this.id = frmDashboard.lbl_id.getText();

    }

    private void obtener_compras() {
        try {
            model = new DefaultTableModel();
            model = icompra.get_compras();

            if (model != null) {
                llenarTabla(this.encabezado());
                this.ocultar_columnas();

            }

        } catch (SQLException e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();

        } catch (Exception e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        materialTextField1 = new principal.MaterialTextField();
        jLabel3 = new javax.swing.JLabel();
        materialTextField2 = new principal.MaterialTextField();
        jLabel2 = new javax.swing.JLabel();
        materialTextField3 = new principal.MaterialTextField();
        jLabel4 = new javax.swing.JLabel();
        materialTextField4 = new principal.MaterialTextField();
        jLabel5 = new javax.swing.JLabel();
        materialTextField5 = new principal.MaterialTextField();
        jLabel6 = new javax.swing.JLabel();
        materialTextField6 = new principal.MaterialTextField();
        jLabel8 = new javax.swing.JLabel();
        materialTextField7 = new principal.MaterialTextField();
        jLabel9 = new javax.swing.JLabel();
        materialTextField8 = new principal.MaterialTextField();
        jLabel10 = new javax.swing.JLabel();
        materialTextField9 = new principal.MaterialTextField();
        registrar = new javax.swing.JButton();
        modificacion = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        materialTextField10 = new principal.MaterialTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        lbl_id = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market.png"))); // NOI18N
        jLabel7.setText("COMPRAS");

        jLabel1.setText("Codigo:");

        jLabel3.setText("Nombre:");

        jLabel2.setText("RFC:");

        jLabel4.setText("T.Producto:");

        jLabel5.setText("Descripcion:");

        jLabel6.setText("Stock:");

        jLabel8.setText("Cantidad:");

        jLabel9.setText("Concepto:");

        jLabel10.setText("Costo Real:");

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        modificacion.setText("Modificar");
        modificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificacionActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setText("Buscar:");

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Todo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetro1.setToolTipText("Empleados\n");
        rSTableMetro1.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rSTableMetro1.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rSTableMetro1.setGrosorBordeFilas(0);
        rSTableMetro1.setGrosorBordeHead(0);
        rSTableMetro1.setRowHeight(20);
        rSTableMetro1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rSTableMetro1FocusGained(evt);
            }
        });
        rSTableMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSTableMetro1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(rSTableMetro1);

        lbl_id.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(materialTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(materialTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(materialTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(materialTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(materialTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(materialTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(materialTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registrar)
                                .addGap(175, 175, 175)
                                .addComponent(modificacion)
                                .addGap(133, 133, 133)
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(materialTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addGap(84, 84, 84)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_id)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(materialTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(materialTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(materialTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(materialTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(materialTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(materialTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(materialTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar)
                    .addComponent(modificacion)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(materialTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton6)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_id)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        try {
            String stock, cantidad, costo_Real;
            String boton = registrar.getText().toString();
            String codigo = materialTextField1.getText().toString().trim();
            String nombre_Producto = materialTextField2.getText().toString().trim();
            String rFC = materialTextField3.getText().toString().trim();
            String tipo_Producto = materialTextField4.getText().toString().trim();
            String descripcion = materialTextField5.getText().toString().trim();
            String concepto = materialTextField8.getText().toString().trim();
            stock = (materialTextField6.getText().toString().trim());
            cantidad = (materialTextField7.getText().toString().trim());
            costo_Real = (materialTextField9.getText().toString().trim());
            this.updateUI();

            if (boton.equalsIgnoreCase("Cancelar")) {
                this.limpiar();
                this.registrar.setText("Registrar");
                this.lbl_id.setText("0");
                this.ocultar_boton(true);
            } else {

                if (codigo.equalsIgnoreCase("") || stock.equalsIgnoreCase("")
                        || rFC.equalsIgnoreCase("") || tipo_Producto.equalsIgnoreCase("")
                        || cantidad.equalsIgnoreCase("")
                        || nombre_Producto.equalsIgnoreCase("")
                        || descripcion.equalsIgnoreCase("")
                        || concepto.equalsIgnoreCase("")
                        || costo_Real.equalsIgnoreCase("")
                        || nombre_Producto.equalsIgnoreCase("")) {
                    alerts.error(StematicConstants.M_OBLIGATE);
                } else {
                    int id_emp = Integer.parseInt(id);
                    if (id_emp == 0) {
                        int axu = Integer.parseInt(lbl_id.getText());
                        alerts.error(StematicConstants.M_EMPLEADO);
                    } else {
                        compraDTO = new CompraDTO(id_emp, 0, codigo,
                                nombre_Producto, rFC, tipo_Producto,
                                descripcion, Integer.parseInt(stock),
                                Double.valueOf(cantidad), concepto,
                                Double.valueOf(costo_Real));
                        int response = icompra.insertar_compra(compraDTO);
                        if (response == 1) {
                            limpiar();
                            this.obtener_compras();
                            alerts.success(StematicConstants.M_INSERT_SUCCESS);
                        } else {
                            alerts.error(StematicConstants.M_ERROR);
                        }
                    }
                }
            }
        } catch (NumberFormatException e) {
            alerts.error("Formato incorrecto de numero");
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();
        } catch (SQLException e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void modificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificacionActionPerformed
        // TODO add your handling code here:
        try {
            String id_compras = lbl_id.getText();
            String stock, cantidad, costo_Real;
            String boton = registrar.getText().toString();
            String codigo = materialTextField1.getText().toString().trim();
            String nombre_Producto = materialTextField2.getText().toString().trim();
            String rFC = materialTextField3.getText().toString().trim();
            String tipo_Producto = materialTextField4.getText().toString().trim();
            String descripcion = materialTextField5.getText().toString().trim();
            String concepto = materialTextField8.getText().toString().trim();
            stock = (materialTextField6.getText().toString().trim());
            cantidad = (materialTextField7.getText().toString().trim());
            costo_Real = (materialTextField9.getText().toString().trim());
            this.updateUI();

            if (codigo.equalsIgnoreCase("") || stock.equalsIgnoreCase("")
                    || rFC.equalsIgnoreCase("") || tipo_Producto.equalsIgnoreCase("")
                    || cantidad.equalsIgnoreCase("")
                    || nombre_Producto.equalsIgnoreCase("")
                    || descripcion.equalsIgnoreCase("")
                    || concepto.equalsIgnoreCase("")
                    || costo_Real.equalsIgnoreCase("")
                    || nombre_Producto.equalsIgnoreCase("")) {
                alerts.error(StematicConstants.M_OBLIGATE);
            } else {
                int id_compra = Integer.parseInt(id_compras);
                if (id_compra == 0) {
                    int axu = Integer.parseInt(lbl_id.getText());
                    alerts.error(StematicConstants.M_EMPLEADO);
                } else {
                    compraDTO = new CompraDTO(0, id_compra, codigo,
                            nombre_Producto, rFC, tipo_Producto,
                            descripcion, Integer.parseInt(stock),
                            Double.valueOf(cantidad), concepto,
                            Double.valueOf(costo_Real));
                    int response = icompra.update_compra(compraDTO);
                    if (response == 1) {
                        limpiar();
                        this.obtener_compras();
                        this.ocultar_boton(true);
                        this.registrar.setText("Registrar");
                        alerts.success(StematicConstants.M_UPDATE_SUCCESS);
                    } else {
                        alerts.error(StematicConstants.M_ERROR);
                    }
                }
            }

        } catch (NumberFormatException e) {
            alerts.error("Formato incorrecto de numero");
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();
        } catch (SQLException e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_modificacionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String id = lbl_id.getText();
            if (id.equalsIgnoreCase("0")) {
                alerts.error(StematicConstants.M_OBLIGATE_ID);
            } else {
                compraDTO = new CompraDTO();
                compraDTO.setmId_compras(Integer.parseInt(id));
                int response = icompra.eliminar_compra(compraDTO);
                if (response == 1) {
                    this.limpiar();
                    this.ocultar_boton(true);
                    this.registrar.setText("Registrar");
                    this.obtener_compras();
                    alerts.success(StematicConstants.M_DELETE_SUCCESS);
                } else {
                    alerts.error(StematicConstants.M_ERROR);
                }
            }
        } catch (SQLException e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String buscar = materialTextField10.getText();

            if (buscar.equalsIgnoreCase("")) {
                alerts.error(StematicConstants.M_OBLIGATE_SEARCH);

            } else {
                compraDTO = new CompraDTO();
                compraDTO.setmNombre_Producto(buscar);
                model = new DefaultTableModel();
                model = icompra.get_compra(compraDTO);
                llenarTabla(this.encabezado());
                this.ocultar_columnas();
                this.materialTextField10.setText("");
            }

        } catch (SQLException e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();

        } catch (Exception e) {
            System.err.println("message:" + e.getMessage());
            e.printStackTrace();

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            this.obtener_compras();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void rSTableMetro1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rSTableMetro1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTableMetro1FocusGained

    private void rSTableMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSTableMetro1MouseClicked
        // TODO add your handling code here:
        int rowIndex = rSTableMetro1.getSelectedRow();
        if (evt.getClickCount() == 1) {
            int colIndex = rSTableMetro1.getSelectedColumn();
            String celda = rSTableMetro1.getValueAt(rowIndex, colIndex).toString();
            rSTableMetro1.setToolTipText(celda);
        } else if (evt.getClickCount() == 2) {

            String id = rSTableMetro1.getValueAt(rowIndex, 1).toString();
            this.ocultar_boton(false);
            this.pasar_columna_caja(materialTextField1, rSTableMetro1.getValueAt(rowIndex, 2).toString());
            this.pasar_columna_caja(materialTextField2, rSTableMetro1.getValueAt(rowIndex, 3).toString());
            this.pasar_columna_caja(materialTextField3, rSTableMetro1.getValueAt(rowIndex, 4).toString());
            this.pasar_columna_caja(materialTextField4, rSTableMetro1.getValueAt(rowIndex, 5).toString());
            this.pasar_columna_caja(materialTextField5, rSTableMetro1.getValueAt(rowIndex, 6).toString());
            this.pasar_columna_caja(materialTextField6, rSTableMetro1.getValueAt(rowIndex, 7).toString());
            this.pasar_columna_caja(materialTextField7, rSTableMetro1.getValueAt(rowIndex, 8).toString());
            this.pasar_columna_caja(materialTextField8, rSTableMetro1.getValueAt(rowIndex, 9).toString());
            this.pasar_columna_caja(materialTextField9, rSTableMetro1.getValueAt(rowIndex, 11).toString());
            lbl_id.setText(id);
            registrar.setText("Cancelar");

        }
    }//GEN-LAST:event_rSTableMetro1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_id;
    private principal.MaterialTextField materialTextField1;
    private principal.MaterialTextField materialTextField10;
    private principal.MaterialTextField materialTextField2;
    private principal.MaterialTextField materialTextField3;
    private principal.MaterialTextField materialTextField4;
    private principal.MaterialTextField materialTextField5;
    private principal.MaterialTextField materialTextField6;
    private principal.MaterialTextField materialTextField7;
    private principal.MaterialTextField materialTextField8;
    private principal.MaterialTextField materialTextField9;
    private javax.swing.JButton modificacion;
    private rojerusan.RSTableMetro rSTableMetro1;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiar() {
        materialTextField1.setText("");
        materialTextField2.setText("");
        materialTextField3.setText("");
        materialTextField4.setText("");
        materialTextField5.setText("");
        materialTextField6.setText("");
        materialTextField7.setText("");
        materialTextField8.setText("");
        materialTextField9.setText("");
    }

    @Override
    public void llenarTabla(Vector vector) {
        rSTableMetro1.setVisible(true);

        model = new DefaultTableModel(model.getDataVector(), vector) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;  // every cell is not editable
            }
        };

        rSTableMetro1.setModel(model);

    }

    @Override
    public void ocultar_boton(boolean status) {
        if (status) {
            modificacion.setVisible(!status);
            jButton5.setVisible(!status);
        } else {
            modificacion.setVisible(!status);
            jButton5.setVisible(!status);
        }
    }

    @Override
    public void ocultar_columnas() {
        //oculta columna del idhabitacion
        rSTableMetro1.getColumnModel().getColumn(0).setMaxWidth(0);
        rSTableMetro1.getColumnModel().getColumn(0).setMinWidth(0);
        rSTableMetro1.getColumnModel().getColumn(0).setPreferredWidth(0);
        rSTableMetro1.getColumnModel().getColumn(1).setMaxWidth(0);
        rSTableMetro1.getColumnModel().getColumn(1).setMinWidth(0);
        rSTableMetro1.getColumnModel().getColumn(1).setPreferredWidth(0);
    }

    @Override
    public void pasar_columna_caja(JTextField field, String valor) {
        field.setText(valor);
    }

    @Override
    public Vector encabezado() {

        try {
            encabezado.clear();
            encabezado.add("Id_Empleado");
            encabezado.add("Id_compras");
            encabezado.add("Codigo");
            encabezado.add("Nombre_Producto");
            encabezado.add("RFC");
            encabezado.add("Tipo_Producto");
            encabezado.add("Descripcion");
            encabezado.add("Stock");
            encabezado.add("Cantidad");
            encabezado.add("Concepto");
            encabezado.add("Fecha_Compra");
            encabezado.add("Costo_Real");

        } catch (Exception e) {
            System.err.println("vector:" + e.getMessage());
            e.printStackTrace();
        }
        return encabezado;
    }
}
